-- MySQL Script generated by MySQL Workbench
-- Thu Nov 22 00:20:11 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`teste2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`teste2` ;

CREATE TABLE IF NOT EXISTS `mydb`.`teste2` (
  `b1` INT NOT NULL,
  `b2` VARCHAR(45) NULL,
  PRIMARY KEY (`b1`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`teste`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`teste` ;

CREATE TABLE IF NOT EXISTS `mydb`.`teste` (
  `a1` INT NOT NULL,
  `a2` VARCHAR(45) NULL,
  `teste2_b1` INT NOT NULL,
  PRIMARY KEY (`a1`),
  INDEX `fk_teste_teste2_idx` (`teste2_b1` ASC) VISIBLE,
  CONSTRAINT `fk_teste_teste2`
    FOREIGN KEY (`teste2_b1`)
    REFERENCES `mydb`.`teste2` (`b1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
